services:

  test:
    container_name: pg_graphql_test
    build:
        context: ..
        dockerfile: ./dockerfiles/db/Dockerfile
        args:
          PG_VERSION: ${PG_VERSION:-15}
    command:
      - ./bin/installcheck
