name: tests
on:
  pull_request:
  push: { branches: [master] }

permissions:
  contents: read

jobs:
  test:
    name: Run tests
    strategy:
      matrix:
        postgres: [14, 15, 16, 17, 18]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build docker images
        run: PG_VERSION=${{ matrix.postgres }} docker compose -f .ci/docker-compose.yml build

      - name: Run tests
        run: PG_VERSION=${{ matrix.postgres }} docker compose -f .ci/docker-compose.yml run test
